// This file is automatically generated. Do not edit it directly.
import { SupabaseClient } from '@supabase/supabase-js';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = {
  auth: {
    async getUser() { return { data: { user: null }, error: null } },
    async getSession() { return { data: { session: null }, error: null } },
    async signInWithPassword() { return { error: new Error('Supabase disabled') } },
    async signUp() { return { error: new Error('Supabase disabled') } },
    async resetPasswordForEmail() { return { error: new Error('Supabase disabled') } },
    async signOut() { return { error: null } },
    onAuthStateChange() { return { data: { subscription: { unsubscribe() {} } } } },
  }
} as unknown as SupabaseClient;
