// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : {
      auth: {
        async getUser() { return { data: { user: null }, error: null } },
        async getSession() { return { data: { session: null }, error: null } },
        async signInWithPassword() { return { error: new Error('Supabase not configured') } },
        async signUp() { return { error: new Error('Supabase not configured') } },
        async resetPasswordForEmail() { return { error: new Error('Supabase not configured') } },
        async signOut() { return { error: null } },
        onAuthStateChange() { return { data: { subscription: { unsubscribe() {} } } } },
      }
    } as any;
